### ISSUE TITLE
Backend system setup

### ISSUE THREAD

**Issue by lhyelinn** [JackyXu-Cool/Team-2130-Machine-Learning-Roulette#10]
Backend system setup to run multiple Machine Learning algorithms

**Comment by ruokun-niu** [comment]
ML Models to implement:

- KMeans
- Neural net
- Naive Bayes

**Comment by JackyXu-Cool** [comment]
Update: Backend API `/upload` and `/training` has been setup and cluster assessment can be obtained if user chooses KMeans.
