### ISSUE TITLE
Select parameters

### ISSUE THREAD

**Issue by ruokun-niu** [JackyXu-Cool/Team-2130-Machine-Learning-Roulette#6]
As a user, I want to choose the parameters so I can figure out the best fit case for  different analysis. 
1. Scenario: User wants to select the parameters for the specific ML models
Given the user has already uploaded the dataset and selected the ML model(s);
when the user selects the related parameters;
then ML models will adjust based on the selection when executed
2. Scenario: User wants to find the random variable seed that generates the optimal results for their dataset.
Given the user has selected their algorithm to use and identified a range of seed variables to try.
When the user generates models for every random seed.
Then they will be able to determine and utilize the best seed for their data in future uses. 
3. Scenario: User does not select any parameters by accident and the ML model they select  requires the user to put at least one parameter 
Given the user does not select any parameter
When they click “run the model”
The model will not run and the user should select at least one parameter to continue.

**Comment by JackyXu-Cool** [comment]
This issue has been resolved.
