### ISSUE TITLE
Uploading datasets

### ISSUE THREAD

**Issue by ruokun-niu** [JackyXu-Cool/Team-2130-Machine-Learning-Roulette#8]
As a registered user, I want to upload my own dataset so I can generate models.
Scenario: A user has a fresh dataset and doesn’t know what models to generate.
Given the user is on the upload page;
When the user selects which dataset to upload;
Then they will be able to select a wide variety of models to start determining the best model to move forward with.
Scenario: The user knows which model they want to generate.
Given the user has already uploaded their dataset;
When the user is selecting their models to generate;
Then they will be able to fine tune their hyperparameters.
Scenario: The user does not have a dataset that they want to use;
Given the user is on the upload page;
When they don’t know what to upload;
Then they can follow links to find publicly available datasets.
Scenario: The dataset exceeds the maximum size allowed 
Given the user has already uploaded their dataset and the size of the dataset has exceeded the limit;
When the user presses the “start training” button;
Then an error will be thrown, notifying the user that the data has exceeded the size limit

**Comment by JackyXu-Cool** [comment]
Users can upload csv dataset they have but are not able to select publicly available dataset (not supported yet and will open another ticket specific for this)
