### ISSUE TITLE
Complete the front-end portions for dataset upload, selecting ML models and hyperparameters

### ISSUE THREAD

**Issue by ruokun-niu** [JackyXu-Cool/Team-2130-Machine-Learning-Roulette#9]
- Users should be able to click on the "upload" button to upload their datasets (in csv format).
- There should be an array of checkboxes that allows the users to select their preffered ML models
- There should be an array of text input fields that allows the users to modify the values of the hyperparameters

**Comment by JackyXu-Cool** [comment]
This has been done. Only thing left is to add a new upload stage for user to upload their y labels to get ML model accuracy. But that is a new requirement discussed with Tommy. Will create another issue to resolve that.

**Comment by ruokun-niu** [comment]
I have already created an issue for that #23
